#!/bin/sh

# Create .env file
cat <<EOT >> .env
DATABASE_URL=${DATABASE_URL}
SERVER_HOST=${SERVER_HOST}
PORT=${PORT}
SERVER_HOST_ADDRESS=${SERVER_HOST_ADDRESS}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=${DB_NAME}
OTP_LENGTH=${OTP_LENGTH}
JWT_SECRETE=${JWT_SECRETE}
JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRETE=${GOOGLE_CLIENT_SECRETE}
GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}
TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
TWILIO_SMS_SENDER=${TWILIO_SMS_SENDER}
EMAIL_HOST=${EMAIL_HOST}
EMAIL_PORT=${EMAIL_PORT}
EMAIL_SENDER=${EMAIL_SENDER}
EMAIL_SENDER_PASSWORD=${EMAIL_SENDER_PASSWORD}
SUPER_ADMIN_FIRST_NAME=${SUPER_ADMIN_FIRST_NAME}
SUPER_ADMIN_LAST_NAME=${SUPER_ADMIN_LAST_NAME}
SUPER_ADMIN_EMAIL=${SUPER_ADMIN_EMAIL}
SUPER_ADMIN_PASSWORD=${SUPER_ADMIN_PASSWORD}
EOT

exec "$@"
