version: "3.8"

services:
  gateway:
    build:
      context: ./user-management-support
    container_name: user_management_support
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USER: natty
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: add-board

  microservice:
    build:
      context: ./user-management-microservice
    container_name: user_management_microservice
    depends_on:
      - database
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USER: natty
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: add-board

  database:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: add-board
      POSTGRES_USER: natty
      POSTGRES_PASSWORD: postres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
