version: '3.8'

services:
  meleket-backend:
    env_file: './.env'
    build:
      context: ./
      args:
        DATABASE_URL: ${DATABASE_URL}
    container_name: meleket_backend
    ports:
      - '8080:8080'
    depends_on:
      - database
    environment:
      - DATABASE_URL=${DATABASE_URL}

  database:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: meleket
      POSTGRES_USER: natty
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
