version: "3.8"

services:
  backend:
    build:
       context: ./
    container_name: meleket_backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USER: natty
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: meleket


  database:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: meleket
      POSTGRES_USER: natty
      POSTGRES_PASSWORD: postres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
